- hosts: localhost
  connection: local
  pre_tasks:
    - name: Install commons packages
      become: yes
      dnf:
        name: "{{item}}"
        state: latest
      with_items:
        - libselinux-python
        - network-manager-applet
        - arandr
  roles:
    - i3
    - urxvt
    - arc-theme
    - vim
    - google-chrome
