---

- name: Install i3 Windows Manager and its dependencies
  sudo: yes
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - i3
    - i3status
    - i3lock

- name: Ensure i3 config folder exist
  file:
    path: ~/.i3
    state: directory

- name: Copy the i3 config file
  copy:
    src: config
    dest: ~/.i3/config

- name: Copy the i3status configuration
  copy:
    src: i3status.conf
    dest: ~/.i3status.conf
