---
- name: Install xsel as clipboard manager
  sudo: yes
  dnf:
    name: xsel
    state: latest

- name: Copy the clipboard perl extension
  sudo: yes
  copy:
    src: clipboard
    dest: /usr/lib64/urxvt/perl/clipboard

- name: Copy Xresources config file for urxvt terminal
  copy:
    src: Xresources
    dest: ~/.Xresources
  notify: Parse Xresources
