---

- name: Set up Vundle plugin
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Copy vimrc configuration file
  copy:
    src: vimrc
    dest: ~/.vimrc
  notify: reload plugin
